export enum PROPERTY_TYPES {
  number = 'number',
  formula = 'formula',
  select = 'select',
  multi_select = 'multi_select',
  status = 'status',
  relation = 'relation',
  rollup = 'rollup',
  title = 'title',
  rich_text = 'rich_text',
  url = 'url',
  people = 'people',
  files = 'files',
  email = 'email',
  phone_number = 'phone_number',
  date = 'date',
  checkbox = 'checkbox',
  created_by = 'created_by',
  created_time = 'created_time',
  last_edited_by = 'last_edited_by',
  last_edited_time = 'last_edited_time',
}
